### ISSUE TITLE
Not working when running `parcel build index.html`

### ISSUE THREAD

**Issue by TechnoTone** [hariroshan/parcel-transformer-elm-assets#1]
I started using this transformer to handle a JPG file I'm referencing within my Elm file. When running Parcel locally, it is working perfectly.

I'm trying to build and deploy my test site on Netlify, but the JPG file is no longer available. I also tested running `parcel build index.html` locally after clearing out my `dist` folder and can see that the JPG file is not included.

**Comment by hariroshan** [comment]
#3 patched this issue.
